# Generated by Django 4.1.4 on 2023-01-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='url_count',
            new_name='endpoint_count',
        ),
    ]
