# Generated by Django 4.1.4 on 2023-01-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='url',
            name='fail_limit',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('status_code', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoints.url')),
            ],
            options={
                'db_table': 'Request',
            },
        ),
    ]
