# Generated by Django 4.1.4 on 2023-01-19 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endpoints', '0002_rename_url_url_address_alter_url_fail_limit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='Endpoint',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='url',
            new_name='enpoint',
        ),
        migrations.AlterModelTable(
            name='endpoint',
            table='Endpoint',
        ),
    ]
