# Generated by Django 4.1.4 on 2023-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_rename_url_endpoint_rename_url_request_enpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
