# Generated by Django 4.1.4 on 2023-01-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_alter_endpoint_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='enpoint',
            new_name='endpoint',
        ),
    ]
